# Generated by Django 2.2.5 on 2019-10-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191001_1553'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bossprofile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='normalprofile',
            managers=[
            ],
        ),
    ]
