# Generated by Django 2.2.3 on 2019-10-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0007_auto_20191002_0130'),
        ('main', '0004_auto_20191001_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossprofile',
            name='mystore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmap.BookStore'),
        ),
    ]
