# Generated by Django 2.2.3 on 2019-10-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bossprofile_mystore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bossprofile',
            name='mystore',
        ),
    ]
