# Generated by Django 2.2.5 on 2019-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='site',
            field=models.URLField(null=True),
        ),
    ]
