# Generated by Django 2.2.5 on 2019-09-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0003_bookstore_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='img',
            field=models.ImageField(null=True, upload_to='store/'),
        ),
    ]
