# Generated by Django 2.2.5 on 2019-09-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0004_bookstore_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
