# Generated by Django 2.2.5 on 2019-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0006_auto_20191002_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='bookstore_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
