# Generated by Django 2.2.5 on 2019-09-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_auto_20190927_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='picture',
            field=models.ImageField(null=True, upload_to='Culture/', verbose_name='이미지 등록'),
        ),
    ]
