# Generated by Django 2.2.5 on 2019-09-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_culture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='group',
            field=models.CharField(choices=[('ET', '기타'), ('CO', '북콘서트'), ('ON', '원데이클래스'), ('CL', '소모임'), ('MO', '영화상영')], default='ET', max_length=7),
        ),
    ]
